version: "3.8"
services:

  express-server:
    build: 
      context: ./back-end
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
      - '5001:5001'
    restart: always
    networks:
      animalwiz-backnet:
      animalwiz-frontnet:
    image: ithinker23/animalwizweb_docker:express-server

  celery-api:
    build:
      context: ./CeleryAPI
      dockerfile: Dockerfile.dev
    depends_on:
      - express-server
    restart: always
    networks:
      animalwiz-backnet:
    image: ithinker23/animalwizweb_docker:celery-api

  react-client:
    build: 
      context: ./front-end
      dockerfile: Dockerfile.dev
    depends_on:
      - express-server
    ports:
      - '3000:3000'
    restart: always
    networks:
      animalwiz-frontnet:
    image: ithinker23/animalwizweb_docker:react-client

networks:
  animalwiz-frontnet:
  animalwiz-backnet: